#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define TAILLE_MAX_NomObjet 18
#define MAX 1000
#define MIN 1
#define MAX_FUITE 3

#define LARGEUR_ECRAN 640
#define HAUTEUR_ECRAN 480

#define DELAI_DEPLACEMENT 3

#endif // CONSTANTES_H_INCLUDED
